#include <sys/mman.h>
#include <stdio.h>

#define pcomment(COMMENT) printf("// %s\n", COMMENT)
#define ppackage(NAME) printf("package %s\n", NAME)
#define pconstblock(EXPS) { printf("\nconst (\n"); {EXPS} printf(")\n"); }
#define pconst(NAME) printf("    %-13s = 0x%x\n", #NAME, NAME)

int main(int argc, char *argvc[]) {
    pcomment("** This file is automatically generated from consts.c. **");
    ppackage("gommap");
    pconstblock(
        pconst(PROT_NONE);
        pconst(PROT_READ);
        pconst(PROT_WRITE);
        pconst(PROT_EXEC);
    )
    pconstblock(
        pconst(MAP_SHARED);
        pconst(MAP_PRIVATE);
        pconst(MAP_FIXED);
        pconst(MAP_ANONYMOUS);
        pconst(MAP_GROWSDOWN);
        pconst(MAP_LOCKED);
        pconst(MAP_NONBLOCK);
        pconst(MAP_NORESERVE);
        pconst(MAP_POPULATE);
    )
    pconstblock(
        pconst(MS_SYNC);
        pconst(MS_ASYNC);
        pconst(MS_INVALIDATE);
    )
    pconstblock(
        pconst(MADV_NORMAL);
        pconst(MADV_RANDOM);
        pconst(MADV_SEQUENTIAL);
        pconst(MADV_WILLNEED);
        pconst(MADV_DONTNEED);
        pconst(MADV_REMOVE);
        pconst(MADV_DONTFORK);
        pconst(MADV_DOFORK);
    )
    return 0;
}
